// utils/constants.js
export const statusMap = {
  Total1: [
    "pending at Screening",
    "Not Interested at screening",
    "moved to Interview",
    "rejected at Screening",
    "no show at Screening",
  ],
  Total2: [
    "put on hold at Interview",
    "selected at Interview",
    "need second opinion at Interview",
    "rejected at Interview",
    "no show at Interview",
    "Moved to HR",
  ],
  Total3: [
    "Sent for Evaluation",
    "Applicant will think about It",
    "selected at Hr",
    "no show at Hr",
    "rejected at Hr",
    "mark_assigned",
    "Spanish Evaluation",
    "backOut",
    "Not Recommended For Hiring",
    "Store Evaluation",
  ],
  // Flattened individual statuses
  "pending at Screening": ["pending at Screening"],
  "No Response At Screening": ["No Response At Screening"],
  "Not Interested at screening": ["Not Interested at screening"],
  "moved to Interview": ["moved to Interview"],
  "rejected at Screening": ["rejected at Screening"],
  "no show at Screening": ["no show at Screening"],
  "put on hold at Interview": ["put on hold at Interview"],
  "selected at Interview": ["selected at Interview"],
  "need second opinion at Interview": ["need second opinion at Interview"],
  "rejected at Interview": ["rejected at Interview"],
  "no show at Interview": ["no show at Interview"],
  "Moved to HR": ["Moved to HR"],
  "Sent for Evaluation": ["Sent for Evaluation"],
  "Applicant will think about It": ["Applicant will think about It"],
  "selected at Hr": ["selected at Hr"],
  "no show at Hr": ["no show at Hr"],
  "rejected at Hr": ["rejected at Hr"],
  mark_assigned: ["mark_assigned"],
  "Spanish Evaluation": ["Spanish Evaluation"], // Note: Original had "Spanish for Evaluation", corrected to match key
  backOut: ["backOut"],
  "Not Recommended For Hiring": ["Not Recommended For Hiring"], // Note: Original had "Not recommeneded for Hiring", corrected typo
  "Store Evaluation": ["Store Evaluation"],
};

export const tableHeaders = [
  "S.No",
  "Created At",
  "Applicant Details",
  "Referred by",
  "Reference ID",
  "Work Location",
  "Screening Manager",
  "Interviewer",
  "HR Name",
  "Status",
  "Joining Date",
  "Comments",
  "Update Comment",
];