version: "3.7"

services:
  mysqldb:
    image: mysql:8.1
    container_name: mysqldb
    hostname: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      - /mysql_data:/var/lib/mysql
      - /database_backups:/backup
    networks:
      - mysql
    profiles:
      - advance
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  dbadmin:
    image: phpmyadmin:latest
    container_name: dbadmin
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8000:80
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - mysql
    profiles:
      - advance
    restart: always

networks:
  mysql:
    driver: bridge
